logging:
  level:
    com.adamkorzeniak: DEBUG
    org.springframework.web: DEBUG

server:
  timezone: Poland

service:
  accuweather:
    url: http://dataservice.accuweather.com
    apiKey: key_temporary_placeholder
    path:
      locations: /locations/v1
    header:
      rate-limit: RateLimit-Limit
      remaining-rate-limit: RateLimit-Remaining